//Development
###
GET http://localhost:3000/
###
GET http://localhost:3000/users/
###
GET http://localhost:3000/users/67617773916aa27240139cf7
###
POST http://localhost:3000/users/ HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Helaman",
    "lastName": "Chino",
    "email": "Helamchino@byui.com",
    "level": 1
    }
}  
###
GET http://localhost:3000/users/6761675f916aa27240139ce4 
###
PUT http://localhost:3000/users/6761675f916aa27240139ce4  HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Milton",
    "lastName": "Chino",
    "email": "mch@byui.com",
    "level": 2
    }
}
### DELETE user
DELETE http://localhost:3000/users/67617773916aa27240139cf7 HTTP/1.1


###
GET http://localhost:3000/docs/
###
GET http://localhost:3000/docs/6761666e916aa27240139cdf 
###
POST http://localhost:3000/docs/ HTTP/1.1
content-type: application/json

{   "doc":{
    "title": "Title 2",
    "description": "Here is the description 2",
    "sentBy": "Milton",
    "updatedBy": "Helaman",
    "source": "/src/img/doc3.pdf",
    "approval": 0
    }
}  

###
PUT http://localhost:3000/docs/6761666e916aa27240139cdf HTTP/1.1
content-type: application/json

{   "doc":{
    "title": "Title",
    "description": "description",
    "sentBy": "Luz",
    "updatedBy": "Helaman",
    "source": "/src/img/doc4.pdf",
    "approval": 1
    }

}  
###
GET http://localhost:3000/docs/6761666e916aa27240139cdf
### DELETE doc
DELETE http://localhost:3000/docs/676176ea916aa27240139cf2 HTTP/1.1



// Production

###
https://cse341-06-g0nu.onrender.com

###
https://cse341-06-g0nu.onrender.com/users/

###
GET https://cse341-06-g0nu.onrender.com/users/6717120629810ddfa37595f2

###
POST https://cse341-06-g0nu.onrender.com/users/ HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Milton",
    "lastName": "Chino",
    "email": "milchino@byui.com",
    "level": 2
    }
}

###
GET https://cse341-06-g0nu.onrender.com/users/6717120629810ddfa37595f2

###
PUT https://cse341-06-g0nu.onrender.com/users/ HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Helaman",
    "lastName": "Chino",
    "email": "helamchino@byui.com",
    "level": 1
    }
}

### DELETE contact
DELETE https://cse341-06-g0nu.onrender.com/contacts/6717120629810ddfa37595f2 HTTP/1.1

###
GET https://cse341-06-g0nu.onrender.com/docs

###
POST https://cse341-06-g0nu.onrender.com/docs/ HTTP/1.1
content-type: application/json

{   "doc":{
    "title": "Title",
    "description": "description",
    "sentBy": "Milton",
    "updatedBy": "Helaman",
    "source": "/src/img/doc4.pdf",
    "approval": 1
    }
}

###
GET https://cse341-06-g0nu.onrender.com/docs/

###
DELETE https://cse341-06-g0nu.onrender.com/docs/
