//Development
###
GET http://localhost:3000/
###
GET http://localhost:3000/users/
###
GET http://localhost:3000/users/6717af075ae4e2146931b6a0
###
POST http://localhost:3000/users/ HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Luz",
    "lastName": "Chino",
    "email": "luzchino@byui.com",
    "level": "admin1"
    }
}  

###
GET http://localhost:3000/docs/
###
GET http://localhost:3000/docs/67341815b2fcdd6c812ae790 
###
POST http://localhost:3000/docs/ HTTP/1.1
content-type: application/json

{   "doc":{
    "title": "Title 2",
    "description": "Here is the description 2",
    "sentBy": "Milton",
    "updatedBy": "Helaman",
    "source": "/src/img/doc2.pdf",
    "approval": 0
    }
}  

###
PUT http://localhost:3000/users/673347b32d506c2aa27812cc HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Luz",
    "lastName": "Chino",
    "email": "luz@byui.com",
    "level": "admin1"
    }
}
### DELETE user
DELETE http://localhost:3000/users/672adb08d494fe719d0a7bfb HTTP/1.1
###
PUT http://localhost:3000/docs/67341815b2fcdd6c812ae790 HTTP/1.1
content-type: application/json

{   "doc":{
    "title": "Title updated",
    "description": "Here is the description updated",
    "sentBy": "Milton",
    "updatedBy": "Luz",
    "source": "/src/img/doc2.pdf",
    "approval": 0
    }
}
### DELETE doc
DELETE http://localhost:3000/docs/67131873 HTTP/1.1



// Production

###
https://cse341-05.onrender.com/

###
https://cse341-05.onrender.com/users/

###
https://cse341-05.onrender.com/users/6717120629810ddfa37595f2

###
POST https://cse341-05.onrender.com/users/ HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Helaman",
    "lastName": "Chino",
    "email": "helamchino@byui.com",
    "level": "admin1"
    }
}

### DELETE contact
DELETE https://cse341-04.onrender.com/contacts/6717120629810ddfa37595f2 HTTP/1.1

